conda-forge/lammps-feedstock

- recipe/build.sh
- recipe/meta.yaml
> Use SHLIB_EXT

- recipe/build.sh
- recipe/meta.yaml
> Library with MPI

- recipe/build.sh
- recipe/meta.yaml
> Fix lammps library

- recipe/meta.yaml
> Increase build number 

- .github/CODEOWNERS
- README.md
- recipe/meta.yaml
> Add ellio167 as maintainer

- recipe/meta.yaml
> Add libcurl as runtime requirement

- README.md
- recipe/build.sh
- recipe/meta.yaml
> Include library.h 

- recipe/build.sh
> Link Library

- recipe/build.sh
- recipe/meta.yaml
> Try to fix library links 

- recipe/build.sh
- recipe/meta.yaml
> Lib fix second try 

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_mpimpichpython2.7.____cpython.yaml
- .ci_support/linux_mpimpichpython3.6.____cpython.yaml
- .ci_support/linux_mpimpichpython3.7.____cpython.yaml
- .ci_support/linux_mpiopenmpipython2.7.____cpython.yaml
- .ci_support/linux_mpiopenmpipython3.6.____cpython.yaml
- .ci_support/linux_mpiopenmpipython3.7.____cpython.yaml
- .ci_support/osx_mpimpichpython2.7.____cpython.yaml
- .ci_support/osx_mpimpichpython3.6.____cpython.yaml
- .ci_support/osx_mpimpichpython3.7.____cpython.yaml
- .ci_support/osx_mpiopenmpipython2.7.____cpython.yaml
- .ci_support/osx_mpiopenmpipython3.6.____cpython.yaml
- .ci_support/osx_mpiopenmpipython3.7.____cpython.yaml
- README.md
- recipe/meta.yaml
> stable_3Mar2020

- .ci_support/linux_64_mpimpichpython3.6.____73_pypy.yaml
- .ci_support/linux_64_mpimpichpython3.6.____cpython.yaml
- .ci_support/linux_64_mpimpichpython3.7.____cpython.yaml
- .ci_support/linux_64_mpimpichpython3.8.____cpython.yaml
- .ci_support/linux_64_mpimpichpython3.9.____cpython.yaml
- .ci_support/linux_64_mpiopenmpipython3.6.____73_pypy.yaml
- .ci_support/linux_64_mpiopenmpipython3.6.____cpython.yaml
- .ci_support/linux_64_mpiopenmpipython3.7.____cpython.yaml
- .ci_support/linux_64_mpiopenmpipython3.8.____cpython.yaml
- .ci_support/linux_64_mpiopenmpipython3.9.____cpython.yaml
- .ci_support/osx_64_mpimpichpython3.6.____73_pypy.yaml
- .ci_support/osx_64_mpimpichpython3.6.____cpython.yaml
- .ci_support/osx_64_mpimpichpython3.7.____cpython.yaml
- .ci_support/osx_64_mpimpichpython3.8.____cpython.yaml
- .ci_support/osx_64_mpimpichpython3.9.____cpython.yaml
- .ci_support/osx_64_mpiopenmpipython3.6.____73_pypy.yaml
- .ci_support/osx_64_mpiopenmpipython3.6.____cpython.yaml
- .ci_support/osx_64_mpiopenmpipython3.7.____cpython.yaml
- .ci_support/osx_64_mpiopenmpipython3.8.____cpython.yaml
- .ci_support/osx_64_mpiopenmpipython3.9.____cpython.yaml
- recipe/meta.yaml
> Just increase the build number to trigger a new build

- recipe/macos_install.patch
- recipe/meta.yaml
> Try christmas release

- .ci_support/linux_64_mpimpichpython3.6.____73_pypy.yaml
- .ci_support/linux_64_mpimpichpython3.6.____cpython.yaml
- .ci_support/linux_64_mpimpichpython3.7.____73_pypy.yaml
- .ci_support/linux_64_mpimpichpython3.7.____cpython.yaml
- .ci_support/linux_64_mpimpichpython3.8.____cpython.yaml
- .ci_support/linux_64_mpimpichpython3.9.____cpython.yaml
- .ci_support/linux_64_mpiopenmpipython3.6.____73_pypy.yaml
- .ci_support/linux_64_mpiopenmpipython3.6.____cpython.yaml
- .ci_support/linux_64_mpiopenmpipython3.7.____73_pypy.yaml
- .ci_support/linux_64_mpiopenmpipython3.7.____cpython.yaml
- .ci_support/linux_64_mpiopenmpipython3.8.____cpython.yaml
- .ci_support/linux_64_mpiopenmpipython3.9.____cpython.yaml
- recipe/meta.yaml
> Separate cpython builds and pypy builds 

- recipe/meta.yaml
> Add mpi4py as additional dependency

- recipe/build.sh
- recipe/meta.yaml
> Add Quip support 

- recipe/meta.yaml
- recipe/python_core.patch
> Fix python library 

- recipe/meta.yaml
> Currently Latte is just downloaded not linked

- recipe/meta.yaml
> Update to latest patch release

- recipe/meta.yaml
- recipe/mliappy.patch
> Patch Mliappy 

- README.md
- recipe/meta.yaml
> Update License from GPL-2.0 to GPL-2.0-only

- recipe/build.sh
- recipe/meta.yaml
> Disable quip download 

- recipe/meta.yaml
> Rebuild - some of the builds failed during the release step

- .ci_support/linux_64_mpimpichpython3.10.____cpython.yaml
- .ci_support/linux_64_mpimpichpython3.8.____cpython.yaml
- .ci_support/linux_64_mpimpichpython3.9.____cpython.yaml
- .ci_support/linux_64_mpiopenmpipython3.10.____cpython.yaml
- .ci_support/linux_64_mpiopenmpipython3.8.____cpython.yaml
- .ci_support/linux_64_mpiopenmpipython3.9.____cpython.yaml
- recipe/build.sh
- recipe/meta.yaml
Just added the "plumed" package with "mode=runtime".
"plumed" itself can be installed separately using existing conda recipies.
> added pakage: plumed+runtime

- recipe/macos_install.patch
- recipe/meta.yaml
> Update to March 28 2023

- recipe/meta.yaml
> Update plugins version

- recipe/build.sh
- recipe/meta.yaml
- recipe/vcsgc_mtp_n2p2.patch
> Link to mlip 3.0

- recipe/meta.yaml
> Downgrade MLIP to 2.0

- .ci_support/linux_64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12fortran_compiler_version12mpimpichnumpy1.22python3.10.____cpython.yaml
- .ci_support/linux_64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12fortran_compiler_version12mpimpichnumpy1.22python3.8.____cpython.yaml
- .ci_support/linux_64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12fortran_compiler_version12mpimpichnumpy1.22python3.9.____73_pypy.yaml
- .ci_support/linux_64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12fortran_compiler_version12mpimpichnumpy1.22python3.9.____cpython.yaml
- .ci_support/linux_64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12fortran_compiler_version12mpimpichnumpy1.23python3.11.____cpython.yaml
- .ci_support/linux_64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12fortran_compiler_version12mpiopenmpinumpy1.22python3.10.____cpython.yaml
- .ci_support/linux_64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12fortran_compiler_version12mpiopenmpinumpy1.22python3.8.____cpython.yaml
- .ci_support/linux_64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12fortran_compiler_version12mpiopenmpinumpy1.22python3.9.____73_pypy.yaml
- .ci_support/linux_64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12fortran_compiler_version12mpiopenmpinumpy1.22python3.9.____cpython.yaml
- .ci_support/linux_64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12fortran_compiler_version12mpiopenmpinumpy1.23python3.11.____cpython.yaml
- .ci_support/migrations/libjpeg_turbo3.yaml
- .ci_support/osx_64_mpimpichnumpy1.22python3.10.____cpython.yaml
- .ci_support/osx_64_mpimpichnumpy1.22python3.8.____cpython.yaml
- .ci_support/osx_64_mpimpichnumpy1.22python3.9.____73_pypy.yaml
- .ci_support/osx_64_mpimpichnumpy1.22python3.9.____cpython.yaml
- .ci_support/osx_64_mpimpichnumpy1.23python3.11.____cpython.yaml
- .ci_support/osx_64_mpiopenmpinumpy1.22python3.10.____cpython.yaml
- .ci_support/osx_64_mpiopenmpinumpy1.22python3.8.____cpython.yaml
- .ci_support/osx_64_mpiopenmpinumpy1.22python3.9.____73_pypy.yaml
- .ci_support/osx_64_mpiopenmpinumpy1.22python3.9.____cpython.yaml
- .ci_support/osx_64_mpiopenmpinumpy1.23python3.11.____cpython.yaml
- .ci_support/osx_arm64_mpimpichnumpy1.22python3.10.____cpython.yaml
- .ci_support/osx_arm64_mpimpichnumpy1.22python3.8.____cpython.yaml
- .ci_support/osx_arm64_mpimpichnumpy1.22python3.9.____cpython.yaml
- .ci_support/osx_arm64_mpimpichnumpy1.23python3.11.____cpython.yaml
- .ci_support/osx_arm64_mpiopenmpinumpy1.22python3.10.____cpython.yaml
- .ci_support/osx_arm64_mpiopenmpinumpy1.22python3.8.____cpython.yaml
- .ci_support/osx_arm64_mpiopenmpinumpy1.22python3.9.____cpython.yaml
- .ci_support/osx_arm64_mpiopenmpinumpy1.23python3.11.____cpython.yaml
- recipe/meta.yaml
> Downgrade mlip - libjpeg-trubo update

- recipe/meta.yaml
> Update to 7Feb2024

- .github/CODEOWNERS
- README.md
- recipe/meta.yaml
> Remove Ryan from the list of maintainers - as requested

- recipe/meta.yaml
- recipe/mpi4py.patch
> Add compatibility for mpi4py 4.0.0

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .ci_support/linux_64_cuda_compiler_version12.6mpimpichpython3.13.____cp313.yaml
- .ci_support/linux_64_cuda_compiler_version12.6mpinompipython3.13.____cp313.yaml
- .ci_support/linux_64_cuda_compiler_version12.6mpiopenmpipython3.13.____cp313.yaml
- .ci_support/linux_64_cuda_compiler_versionNonempimpichpython3.13.____cp313.yaml
- .ci_support/linux_64_cuda_compiler_versionNonempinompipython3.13.____cp313.yaml
- .ci_support/linux_64_cuda_compiler_versionNonempiopenmpipython3.13.____cp313.yaml
- .ci_support/migrations/python313.yaml
- .ci_support/osx_64_mpimpichpython3.13.____cp313.yaml
- .ci_support/osx_64_mpinompipython3.13.____cp313.yaml
- .ci_support/osx_64_mpiopenmpipython3.13.____cp313.yaml
- .ci_support/osx_arm64_mpimpichpython3.13.____cp313.yaml
- .ci_support/osx_arm64_mpinompipython3.13.____cp313.yaml
- .ci_support/osx_arm64_mpiopenmpipython3.13.____cp313.yaml
- README.md
- recipe/meta.yaml
> Python 3.13 migration
